baseURL = "https://routes.tracestrack.com/"
languageCode = "en"
title = "OpenStreetMap Routes Index"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "homepage"
enableEmoji = true
paginate = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
