baseURL = "https://b82b7d54.osm-routes-index.pages.dev/"
languageCode = "en"
title = "Monochrome"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "homepage"
enableEmoji = true
paginate = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
