[homepage]
contentDir = "content/homepage"
languageName = "Homepage"
weight = 1

[US]
contentDir = "content/US"
languageName = "United States"
languageCode = "US"
weight = 1

[CN]
contentDir = "content/CN"
languageName = "China/中国"
languageCode = "CN"
weight = 2

[NL]
contentDir = "content/NL"
languageName = "Netherlands/Nederland"
languageCode = "NL"
weight = 2

[BE]
contentDir = "content/BE"
languageName = "Belgium/Belgie"
languageCode = "BE"
weight = 2
