[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SG/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/SG/subway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/SG/bicycle/"
  weight = 1
