[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/US/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/US/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/US/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/US/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/US/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/US/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/US/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/US/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/US/ferry/"
  weight = 1
