[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/EE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/EE/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/EE/train/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/EE/bicycle/"
  weight = 1
