[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/KG/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/KG/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/KG/train/"
  weight = 1
