[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/KE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/KE/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/KE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/KE/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/KE/hiking/"
  weight = 1
