[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/TW/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/TW/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/TW/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/TW/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/TW/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/TW/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/TW/hiking/"
  weight = 1
