[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NC/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/NC/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/NC/hiking/"
  weight = 1
