[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/VE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/VE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/VE/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/VE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/VE/railway/"
  weight = 1
