[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/PS/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/PS/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/PS/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/PS/train/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/PS/hiking/"
  weight = 1
