[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SY/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SY/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/SY/bicycle/"
  weight = 1
