[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/ME/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/ME/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/ME/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/ME/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/ME/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/ME/hiking/"
  weight = 1
