[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/GR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/GR/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/GR/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/GR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/GR/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/GR/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/GR/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/GR/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/GR/ferry/"
  weight = 1
