[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SZ/bus/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SZ/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/SZ/hiking/"
  weight = 1
