[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MN/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MN/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MN/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/MN/railway/"
  weight = 1
