[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CU/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CU/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CU/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CU/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/CU/hiking/"
  weight = 1
