[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/ID/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/ID/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/ID/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/ID/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/ID/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/ID/bicycle/"
  weight = 1
