[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SK/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SK/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/SK/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/SK/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SK/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/SK/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/SK/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/SK/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/SK/ferry/"
  weight = 1
