[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SN/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SN/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/SN/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SN/railway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/SN/ferry/"
  weight = 1
