[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/RO/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/RO/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/RO/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/RO/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/RO/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/RO/bicycle/"
  weight = 1
