[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/LA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LA/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/LA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/LA/railway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/LA/ferry/"
  weight = 1
