[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CM/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CM/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CM/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CM/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/CM/hiking/"
  weight = 1
