[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AL/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AL/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AL/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AL/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/AL/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/AL/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/AL/ferry/"
  weight = 1
