[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/PH/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/PH/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/PH/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/PH/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/PH/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/PH/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/PH/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/PH/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/PH/ferry/"
  weight = 1
