[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/TR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/TR/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/TR/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/TR/train/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/TR/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/TR/hiking/"
  weight = 1
