[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/QA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/QA/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/QA/subway/"
  weight = 1
