[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MD/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MD/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MD/train/"
  weight = 1
