[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/FI/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/FI/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/FI/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/FI/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/FI/railway/"
  weight = 1
