[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AR/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AR/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AR/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/AR/bicycle/"
  weight = 1
