[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/BE/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/BE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BE/railway/"
  weight = 1
