[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/UA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/UA/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/UA/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/UA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/UA/railway/"
  weight = 1
