[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/IE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/IE/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/IE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/IE/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/IE/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/IE/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/IE/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/IE/ferry/"
  weight = 1
