[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/PL/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/PL/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/PL/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/PL/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/PL/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/PL/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/PL/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/PL/horse/"
  weight = 1
