[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/FR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/FR/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/FR/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/FR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/FR/railway/"
  weight = 1
