[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SM/bus/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SM/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/SM/hiking/"
  weight = 1
