[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AU/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AU/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AU/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AU/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AU/railway/"
  weight = 1
