[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/IS/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/IS/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/IS/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/IS/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/IS/ferry/"
  weight = 1
