[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/GB/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/GB/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/GB/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/GB/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/GB/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/GB/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/GB/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/GB/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/GB/ferry/"
  weight = 1
