[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AT/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AT/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AT/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AT/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AT/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/AT/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/AT/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/AT/horse/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/AT/ferry/"
  weight = 1
