[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NL/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NL/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/NL/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NL/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/NL/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/NL/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/NL/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/NL/horse/"
  weight = 1
