[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AE/subway/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AE/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/AE/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/AE/ferry/"
  weight = 1
