[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/DK/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/DK/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/DK/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/DK/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/DK/railway/"
  weight = 1
