[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BA/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/BA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BA/railway/"
  weight = 1
