[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NG/road/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/NG/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NG/train/"
  weight = 1
