[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CH/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CH/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/CH/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CH/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CH/railway/"
  weight = 1
