[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BG/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BG/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/BG/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/BG/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BG/railway/"
  weight = 1
