[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AT/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AT/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AT/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AT/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/AT/railway/"
  weight = 1
