[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MY/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MY/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/MY/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MY/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/MY/railway/"
  weight = 1
