[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NA/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/NA/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/NA/hiking/"
  weight = 1
