[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/DZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/DZ/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/DZ/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/DZ/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/DZ/railway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/DZ/ferry/"
  weight = 1
