[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/LU/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LU/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/LU/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/LU/railway/"
  weight = 1
