[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BD/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BD/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/BD/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/BD/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BD/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/BD/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/BD/ferry/"
  weight = 1
