[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AZ/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AZ/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/AZ/train/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/AZ/hiking/"
  weight = 1
