[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/TN/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/TN/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/TN/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/TN/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/TN/railway/"
  weight = 1
