[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CL/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CL/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/CL/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CL/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CL/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/CL/bicycle/"
  weight = 1
