[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/IT/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/IT/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/IT/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/IT/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/IT/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/IT/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/IT/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/IT/horse/"
  weight = 1
