[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/ZA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/ZA/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/ZA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/ZA/railway/"
  weight = 1
