[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/PT/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/PT/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/PT/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/PT/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/PT/railway/"
  weight = 1
