[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/OM/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/OM/bus/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/OM/hiking/"
  weight = 1
