[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/LB/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LB/bus/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/LB/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/LB/hiking/"
  weight = 1
