[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MA/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/MA/railway/"
  weight = 1
