[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/GB/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/GB/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/GB/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/GB/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/GB/railway/"
  weight = 1
