[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/EC/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/EC/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/EC/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/EC/train/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/EC/hiking/"
  weight = 1
