[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/UY/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/UY/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/UY/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/UY/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/UY/hiking/"
  weight = 1
