[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MM/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MM/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/MM/subway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/MM/ferry/"
  weight = 1
