[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AX/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AX/bus/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/AX/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/AX/ferry/"
  weight = 1
