[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/HK/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/HK/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/HK/subway/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/HK/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/HK/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/HK/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/HK/ferry/"
  weight = 1
