[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CG/road/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CG/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CG/railway/"
  weight = 1
