[[navbar]]
  identifier = "road"
  name = "公路"
  url = "/cn/road/"
  weight = 1

[[navbar]]
  identifier = "railway"
  name = "铁路"
  url = "/cn/railway/"
  weight = 2

[[navbar]]
  identifier = "train"
  name = "火车"
  url = "/cn/train/"
  weight = 2

[[navbar]]
  identifier = "subway"
  name = "地铁"
  url = "/cn/subway/"
  weight = 3

[[navbar]]
  identifier = "bus"
  name = "公交"
  url = "/cn/bus/"
  weight = 4