[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MK/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MK/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MK/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/MK/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/MK/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/MK/hiking/"
  weight = 1
