[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/EG/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/EG/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/EG/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/EG/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/EG/railway/"
  weight = 1
