[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/JP/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/JP/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/JP/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/JP/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/JP/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/JP/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/JP/hiking/"
  weight = 1
