[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/KP/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/KP/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/KP/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/KP/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/KP/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/KP/hiking/"
  weight = 1
