[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/ES/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/ES/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/ES/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/ES/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/ES/railway/"
  weight = 1
