[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/GE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/GE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/GE/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/GE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/GE/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/GE/hiking/"
  weight = 1
