[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BY/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BY/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/BY/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/BY/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BY/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/BY/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/BY/hiking/"
  weight = 1
