[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NO/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NO/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/NO/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NO/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/NO/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/NO/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/NO/hiking/"
  weight = 1
