[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/US/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/US/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/US/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/US/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/US/railway/"
  weight = 1
