[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/JE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/JE/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/JE/bicycle/"
  weight = 1
