[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CA/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CA/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/CA/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CA/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CA/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/CA/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/CA/hiking/"
  weight = 1
[[navbar]]
  identifier = "horse"
  name = "Horse"
  url = "/CA/horse/"
  weight = 1
