[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NL/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NL/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/NL/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NL/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/NL/railway/"
  weight = 1
