[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/IE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/IE/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/IE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/IE/railway/"
  weight = 1
