[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/RU/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/RU/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/RU/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/RU/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/RU/railway/"
  weight = 1
