[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/LV/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LV/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/LV/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/LV/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/LV/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/LV/hiking/"
  weight = 1
