[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LI/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/LI/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/LI/hiking/"
  weight = 1
