[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MR/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/MR/railway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/MR/ferry/"
  weight = 1
