[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NZ/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/NZ/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/NZ/railway/"
  weight = 1
