[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SK/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SK/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/SK/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/SK/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SK/railway/"
  weight = 1
