[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/TJ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/TJ/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/TJ/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/TJ/railway/"
  weight = 1
