[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/DE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/DE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/DE/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/DE/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/DE/railway/"
  weight = 1
