[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/AE/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/AE/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/AE/subway/"
  weight = 1
