[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/UZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/UZ/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/UZ/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/UZ/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/UZ/railway/"
  weight = 1
