[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/MX/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/MX/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/MX/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/MX/train/"
  weight = 1
