[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/VN/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/VN/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/VN/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/VN/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/VN/railway/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/VN/ferry/"
  weight = 1
