[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/CZ/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/CZ/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/CZ/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/CZ/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/CZ/railway/"
  weight = 1
