[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/LT/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/LT/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/LT/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/LT/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/LT/railway/"
  weight = 1
