[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/BF/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/BF/bus/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/BF/railway/"
  weight = 1
