[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/HR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/HR/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/HR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/HR/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/HR/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/HR/hiking/"
  weight = 1
