[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/KR/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/KR/bus/"
  weight = 1
[[navbar]]
  identifier = "subway"
  name = "Subway"
  url = "/KR/subway/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/KR/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/KR/railway/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/KR/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/KR/ferry/"
  weight = 1
