[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/SI/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/SI/bus/"
  weight = 1
[[navbar]]
  identifier = "train"
  name = "Train"
  url = "/SI/train/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/SI/railway/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/SI/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/SI/hiking/"
  weight = 1
