[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/-/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/-/bus/"
  weight = 1
[[navbar]]
  identifier = "railway"
  name = "Railway"
  url = "/-/railway/"
  weight = 1
