[[navbar]]
  identifier = "road"
  name = "Road"
  url = "/NI/road/"
  weight = 1
[[navbar]]
  identifier = "bus"
  name = "Bus"
  url = "/NI/bus/"
  weight = 1
[[navbar]]
  identifier = "bicycle"
  name = "Bicycle"
  url = "/NI/bicycle/"
  weight = 1
[[navbar]]
  identifier = "hiking"
  name = "Hiking"
  url = "/NI/hiking/"
  weight = 1
[[navbar]]
  identifier = "ferry"
  name = "Ferry"
  url = "/NI/ferry/"
  weight = 1
